name: "Build Kaos"
run-name: "Run by ${{ github.actor }}"
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    container:
      image: erlang:28
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - run: rebar3 test
      - name: Upload EUnit coverage reports
        if: always()
        uses: actions/upload-artifacts@v4
        with:
          name: coverage
          path: ./_build/test/cover/**/*.html
